name: "publish npm"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Login to npm
        run: npm login --registry https://registry.npmjs.org --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Run tests
        run: npm test
        working-directory: .

      - name: Publish the package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        working-directory: .